### ISSUE TITLE
I Know There Is A LOt Lot Of Not Working Links Can Someone Help Me?

### ISSUE THREAD

**Issue by adasjusk** [adasjusk/OrangInstall#1]
Write Links To Fix Code Of **PROGINSTALL.cmd**

**Comment by OCEANOFANYTHINGOFFICIAL** [comment]
What Exactly you need? Can You Please explain more?

**Comment by adasjusk** [comment]
> What Exactly you need? Can You Please explain more?

Ok. So this script had problems with inactive download links
